### ISSUE TITLE
Is openVX open sourced? I cannot find the definition of vxuGaussianPyramid

### ISSUE THREAD

**Issue by ALittleBug** [KhronosGroup/OpenVX-sample-impl#28]

**Comment by jessegv** [comment]
This github project has an open source "sample" implementation of OpenVX provided by the Khronos OpenVX working group.  It does not claim to be optimized, but may be a good starting point for others to contribute to or use as-is with no guarantees.  Different chip vendors may have optimized implementations that they maintain and distribute on their own terms since OpenVX is an Open Standard API interface (see conformant implementations at https://www.khronos.org/openvx/).  There are 2 other related github projects that the Khronos group maintains: 

1. OpenVX Specification documentation and headers: https://github.com/KhronosGroup/OpenVX-api-docs
2. OpenVX Conformant Test Suite: https://github.com/KhronosGroup/OpenVX-cts

Specifically, the declaration of the vxuGaussianPyaramid is in the api-docs project, here: https://github.com/KhronosGroup/OpenVX-api-docs/blob/51851eceaab76bfba30e91617352c8ea49a8ca72/include/VX/vxu.h#L312

And the definition of this vxuGaussianPyramid is in this project, located here:
https://github.com/KhronosGroup/OpenVX-sample-impl/blob/df31e0189b8367bba92d901e79134ffe6eec66e4/sample/vxu/vx_utility.c#L609
